"""Periodic audit-log review (HIPAA 164.308(a)(1)(ii)(D) information system activity review).

Revision ID: 055
Revises: 054
Create Date: 2026-10-01

One row per tenant per review period (monthly by default, generated by Celery Beat):
a summary of the security-relevant activity in the audit log — failed sign-ins and
lockouts, emergency access, integrity alarms, exports / disclosures, after-hours reads
of patient data, the most active readers — and who reviewed it, when, with what notes.
The summary is computed once and kept, so the review attests to exactly what was shown.
"""
from __future__ import annotations

import os

import sqlalchemy as sa
from alembic import op

revision = "055"
down_revision = "054"
branch_labels = None
depends_on = None

TABLE = "audit_reviews"
TENANT_EXPR = (
    "tenant_id = current_setting('app.tenant_id', true) "
    "OR current_setting('app.platform', true) = 'on'"
)


def _app_role(conn) -> str | None:
    user = os.environ.get("POSTGRES_APP_USER", "").strip()
    if not user:
        return None
    if conn.execute(sa.text("SELECT 1 FROM pg_roles WHERE rolname = :u"), {"u": user}).first():
        return conn.execute(sa.text("SELECT quote_ident(:u)"), {"u": user}).scalar_one()
    return None


def upgrade() -> None:
    conn = op.get_bind()
    op.create_table(
        TABLE,
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), sa.ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("findings_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("generated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("reviewed_by", sa.String(36), sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True),
        sa.Column("reviewed_by_username", sa.String(128), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_notes", sa.Text(), nullable=True),
        sa.UniqueConstraint("tenant_id", "period_start", name="uq_audit_review_period"),
    )
    op.create_index(f"ix_{TABLE}_tenant_period", TABLE, ["tenant_id", "period_start"])
    conn.execute(sa.text(f"ALTER TABLE {TABLE} ENABLE ROW LEVEL SECURITY"))
    conn.execute(sa.text(f"ALTER TABLE {TABLE} FORCE ROW LEVEL SECURITY"))
    conn.execute(sa.text(
        f"CREATE POLICY tenant_isolation ON {TABLE} FOR ALL "
        f"USING ({TENANT_EXPR}) WITH CHECK ({TENANT_EXPR})"
    ))
    role = _app_role(conn)
    if role:
        # Reviews are marked, never removed.
        conn.execute(sa.text(f"GRANT SELECT, INSERT, UPDATE ON {TABLE} TO {role}"))
        conn.execute(sa.text(f"REVOKE DELETE, TRUNCATE ON {TABLE} FROM {role}"))


def downgrade() -> None:
    op.drop_table(TABLE)
