from __future__ import annotations

"""What the AI workers may see of a patient: the HIPAA Safe Harbor boundary (164.514(b)).

Pure rules (no I/O). ``infrastructure/orthanc/deidentify.py`` applies them to every DICOM
file a pipeline downloads, and to the study record a pipeline is given, before anything
reaches a worker's working directory.

Kept, because inference needs them and they are not Safe Harbor identifiers: modality and
acquisition parameters, pixel data, sex, age (except 90+, grouped), weight and height
(SUV), times of day (decay correction), descriptions of the study/series/protocol, and the
DICOM UIDs. UIDs are generated by the modality, not derived from patient information, and
serve as the platform's internal re-identification code (164.514(c)) — results are linked
back to the patient only by the task, never by the worker.

Dates are not removed but *shifted*: every date in the file moves by the same offset so the
study date becomes 1 January of its year. Intervals (injection → scan, prior → current)
are preserved; no real date other than the year leaves the boundary.
"""

# Replaced with a pseudonym (salted hash of the original value).
PSEUDONYMISED_TAGS: tuple[str, ...] = ("PatientID",)

# Blanked (kept present, empty: several are DICOM type 2).
BLANKED_TAGS: tuple[str, ...] = (
    "PatientName",
    "AccessionNumber",
    "StudyID",
    "ReferringPhysicianName",
    "InstitutionName",
    "InstitutionalDepartmentName",
    "StationName",
    "PerformingPhysicianName",
    "OperatorsName",
    "PhysiciansOfRecord",
    "NameOfPhysiciansReadingStudy",
    "RequestingPhysician",
    "ContentCreatorName",
    "PerformedStationName",
    "ScheduledPerformingPhysicianName",
)

# Removed entirely.
REMOVED_TAGS: tuple[str, ...] = (
    "PatientBirthDate",
    "PatientBirthTime",
    "PatientBirthName",
    "PatientMotherBirthName",
    "OtherPatientIDs",
    "OtherPatientIDsSequence",
    "OtherPatientNames",
    "IssuerOfPatientID",
    "PatientAddress",
    "PatientTelephoneNumbers",
    "PatientTelecomInformation",
    "CountryOfResidence",
    "RegionOfResidence",
    "MilitaryRank",
    "BranchOfService",
    "MedicalRecordLocator",
    "PatientInsurancePlanCodeSequence",
    "InsurancePlanIdentification",
    "Occupation",
    "EthnicGroup",
    "PatientReligiousPreference",
    "AdditionalPatientHistory",
    "PatientComments",
    "ImageComments",
    "StudyComments",
    "InstitutionAddress",
    "ReferringPhysicianAddress",
    "ReferringPhysicianTelephoneNumbers",
    "ReferringPhysicianIdentificationSequence",
    "PhysiciansOfRecordIdentificationSequence",
    "PerformingPhysicianIdentificationSequence",
    "OperatorIdentificationSequence",
    "DeviceSerialNumber",
    "RequestAttributesSequence",
    "RequestedProcedureID",
    "PerformedProcedureStepID",
    "ScheduledProcedureStepID",
    "AdmissionID",
    "ResponsiblePerson",
    "ResponsibleOrganization",
    "ReferencedPatientSequence",
    "PersonName",
)

AGE_CAP_YEARS = 90  # Safe Harbor: ages over 89 aggregated into "90 or older"


def cap_age(age: str | None) -> str | None:
    """DICOM AS value ("045Y", "011M") with ages above 89 years reported as 090Y."""
    if not age:
        return age
    text = age.strip().upper()
    if text.endswith("Y") and text[:-1].isdigit() and int(text[:-1]) >= AGE_CAP_YEARS:
        return f"{AGE_CAP_YEARS:03d}Y"
    return text


DEIDENTIFICATION_METHOD = (
    "Cortex worker boundary: HIPAA Safe Harbor identifiers removed or blanked, PatientID "
    "pseudonymised, private tags removed, dates shifted to a year anchor, ages >89 grouped"
)
