#!/usr/bin/env bash
# Start (or update) the production stack.
#
#   sudo ops/deploy/up.sh [--build] [--skip-preflight] [--first-deploy] [--prepare-only]
#                         [-- extra compose args]
#
#   1. decrypts /etc/mrcv/secrets.enc.env (SOPS + age, key /etc/mrcv/age.key) and joins it
#      with the plain settings in /etc/mrcv/mrcv.env into /run/mrcv/.env — tmpfs only,
#      0600, never on a disk;
#   2. writes the Orthanc storage master key to /run/mrcv/orthanc-keys/ (tmpfs);
#   3. runs ops/deploy/preflight.sh and refuses to start if anything FAILs;
#   4. docker compose -f docker-compose.yml -f docker-compose.prod.yml [-f overlays] up -d
#      (profile "letsencrypt" unless you bring your own certificate).
#   --prepare-only stops after step 2 (renders /run/mrcv for manual docker compose use,
#   e.g. a restore onto a stack whose application services must not start yet).
#
# Run by ops/systemd/mrcv-stack.service at boot. Paths can be overridden with
# MRCV_DIR (repo checkout, default /opt/mrcv), MRCV_ETC (/etc/mrcv), MRCV_RUNTIME_DIR.
set -Eeuo pipefail
umask 077

MRCV_DIR="${MRCV_DIR:-/opt/mrcv}"
MRCV_ETC="${MRCV_ETC:-/etc/mrcv}"
RUN="${MRCV_RUNTIME_DIR:-/run/mrcv}"
BUILD=""
PREFLIGHT=1
PREFLIGHT_ARGS=()
PREPARE_ONLY=0
EXTRA=()
while [ $# -gt 0 ]; do
  case "$1" in
    --build) BUILD="--build"; shift ;;
    --skip-preflight) PREFLIGHT=0; shift ;;
    --first-deploy) PREFLIGHT_ARGS+=(--first-deploy); shift ;;
    --prepare-only) PREPARE_ONLY=1; shift ;;
    --) shift; EXTRA=("$@"); break ;;
    -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

log() { printf 'mrcv-up: %s\n' "$*" >&2; }
die() { log "ERROR: $*"; exit 1; }

[ "$(id -u)" = 0 ] || die "run as root"
[ -r "$MRCV_ETC/mrcv.env" ] || die "$MRCV_ETC/mrcv.env missing (copy ops/deploy/mrcv.env.example)"
[ -r "$MRCV_ETC/secrets.enc.env" ] || die "$MRCV_ETC/secrets.enc.env missing (ops/deploy/secrets-init.sh)"
export SOPS_AGE_KEY_FILE="${SOPS_AGE_KEY_FILE:-$MRCV_ETC/age.key}"
[ -r "$SOPS_AGE_KEY_FILE" ] || die "age key $SOPS_AGE_KEY_FILE missing"

# ── 1. runtime env on tmpfs ─────────────────────────────────────────────────
mkdir -p "$RUN"
[ "$(findmnt -no FSTYPE -T "$RUN")" = tmpfs ] || die "$RUN is not on tmpfs; refusing to write secrets to disk"
chmod 0700 "$RUN"
tmp="$(mktemp "$RUN/.env.XXXXXX")"
trap 'rm -f -- "$tmp"' EXIT
{
  printf '# GENERATED by ops/deploy/up.sh at %s - do not edit (tmpfs, gone at reboot).\n' "$(date -u +%FT%TZ)"
  grep -vE '^\s*(#|$)' "$MRCV_ETC/mrcv.env"
  sops --decrypt --input-type dotenv --output-type dotenv "$MRCV_ETC/secrets.enc.env" \
    | grep -vE '^\s*(#|$)'
  printf 'MRCV_ENV_FILE=%s/.env\nMRCV_RUNTIME_DIR=%s\n' "$RUN" "$RUN"
} > "$tmp"
chmod 0600 "$tmp"
mv -f "$tmp" "$RUN/.env"
trap - EXIT

envval() { { grep -E "^$1=" "$RUN/.env" || true; } | tail -1 | cut -d= -f2-; }

# ── 2. Orthanc storage master key (file, as the plugin requires) ───────────────
mkdir -p "$RUN/orthanc-keys"
chmod 0700 "$RUN/orthanc-keys"
key="$(envval ORTHANC_STORAGE_MASTER_KEY)"
[ -n "$key" ] || die "ORTHANC_STORAGE_MASTER_KEY missing from the secrets"
printf '%s\n' "$key" > "$RUN/orthanc-keys/master.key"
# Previous keys stay readable after a rotation (ops/KEYS.md): ORTHANC_STORAGE_PREVIOUS_KEY_<id>
{ grep -E '^ORTHANC_STORAGE_PREVIOUS_KEY_[0-9]+=' "$RUN/.env" || true; } | while IFS='=' read -r name value; do
  printf '%s\n' "$value" > "$RUN/orthanc-keys/previous-${name##*_}.key"
done
chmod 0400 "$RUN/orthanc-keys/"*.key
# Orthanc reads the key list from config: current MasterKey + every PreviousMasterKey
# (mounted as /etc/orthanc/zz-storage-keys.json, deep-merged into orthanc.prod.json).
key_id="$(envval ORTHANC_STORAGE_KEY_ID)"; key_id="${key_id:-1}"
previous=""
for f in "$RUN/orthanc-keys"/previous-*.key; do
  [ -e "$f" ] || continue
  id="${f##*/previous-}"; id="${id%.key}"
  previous="${previous:+$previous, }[$id, \"/run/orthanc-keys/previous-$id.key\"]"
done
printf '{"AwsS3Storage": {"StorageEncryption": {"MasterKey": [%s, "/run/orthanc-keys/master.key"], "PreviousMasterKeys": [%s]}}}\n' \
  "$key_id" "$previous" > "$RUN/orthanc-keys/storage-keys.json"
chmod 0444 "$RUN/orthanc-keys/storage-keys.json"
if [ "$PREPARE_ONLY" = 1 ]; then
  log "prepared $RUN (env file + Orthanc keys); not starting anything (--prepare-only)"
  exit 0
fi

# ── 3. preflight ──────────────────────────────────────────────────────────────
if [ "$PREFLIGHT" = 1 ]; then
  MRCV_DIR="$MRCV_DIR" MRCV_ENV_FILE="$RUN/.env" bash "$MRCV_DIR/ops/deploy/preflight.sh" "${PREFLIGHT_ARGS[@]}" \
    || die "preflight failed - nothing was started (fix the FAIL lines above)"
else
  log "WARNING: --skip-preflight: starting without the compliance checks"
fi

# ── 4. compose up ─────────────────────────────────────────────────────────────
files=(-f "$MRCV_DIR/docker-compose.yml" -f "$MRCV_DIR/docker-compose.prod.yml")
for overlay in $(envval MRCV_COMPOSE_OVERLAYS | tr ',' ' '); do
  files+=(-f "$MRCV_DIR/$overlay")
done
profiles=()
[ -z "$(envval TLS_CERT_FILE)" ] && profiles+=(--profile letsencrypt)
# Optional services, e.g. MRCV_COMPOSE_PROFILES=shadow (isolated A/B shadow worker).
for p in $(envval MRCV_COMPOSE_PROFILES | tr ',' ' '); do profiles+=(--profile "$p"); done

cd "$MRCV_DIR"
log "starting: ${files[*]} ${profiles[*]}"
docker compose --env-file "$RUN/.env" "${files[@]}" "${profiles[@]}" up -d --remove-orphans $BUILD "${EXTRA[@]}"
log "up. Health: docker compose ps; curl -fsS https://\$PUBLIC_DOMAIN/health"
