#!/usr/bin/env bash
# Render /opt/mrcv/.env (mode 0600, root) at boot from:
#   1. /etc/mrcv/mrcv.env      NON-secret settings (PUBLIC_DOMAIN, GCP_PROJECT, CERTBOT_EMAIL,
#                              feature flags ...). Template: ops/providers/gcp/mrcv.env.example
#   2. Secret Manager          one secret per variable, id "${SECRET_PREFIX}<VAR_NAME>"
#                              (default prefix "mrcv-", e.g. mrcv-POSTGRES_PASSWORD)
#   3. derived values          CELERY_BROKER_URL / CELERY_RESULT_BACKEND (from REDIS_PASSWORD)
#                              ORTHANC_BASIC_AUTH (base64 of ORTHANC_USERNAME:ORTHANC_PASSWORD)
#
# Runs as ops/systemd/mrcv-render-env.service before mrcv-stack.service. Needs the VM
# service account to hold roles/secretmanager.secretAccessor. Secret VALUES are never
# printed or passed on a command line; only variable names are logged.
#
# Usage: sudo ops/providers/gcp/render-env.sh            (env overrides: MRCV_DIR, BASE_ENV,
#                                               SECRET_PREFIX, GCP_PROJECT)
set -Eeuo pipefail
umask 077

MRCV_DIR="${MRCV_DIR:-/opt/mrcv}"
BASE_ENV="${BASE_ENV:-/etc/mrcv/mrcv.env}"
SECRET_PREFIX="${SECRET_PREFIX:-mrcv-}"
OUT="${MRCV_DIR}/.env"

log() { printf 'render-env: %s\n' "$*" >&2; }
die() { log "ERROR: $*"; exit 1; }

# Secrets the stack cannot run without (see .env.example / docker-compose.yml).
REQUIRED_SECRETS=(
    POSTGRES_PASSWORD
    POSTGRES_APP_PASSWORD
    REDIS_PASSWORD
    MINIO_SECRET_KEY
    ORTHANC_PASSWORD
    ORTHANC_WEBHOOK_SECRET
    JWT_SECRET_KEY
    PHI_HASH_SALT
    SECRET_KEY
)
# Fetched when present; otherwise the value from mrcv.env / the compose default is used.
OPTIONAL_SECRETS=(
    ORTHANC_USERNAME
    MINIO_ACCESS_KEY
    API_KEY
    HF_TOKEN
    AUDIT_CHAIN_PREVIOUS_MASTER_KEY
    ORTHANC_DICOM_MODALITIES
)
# Never taken from anywhere in production (GEMINI_BACKEND=vertex uses the VM identity).
FORBIDDEN=(GEMINI_API_KEY CELERY_BROKER_URL CELERY_RESULT_BACKEND ORTHANC_BASIC_AUTH)

[ -r "${BASE_ENV}" ] || die "${BASE_ENV} not found (copy ops/providers/gcp/mrcv.env.example there)"
command -v gcloud >/dev/null || die "gcloud CLI not installed"

base_value() {  # value of NAME in BASE_ENV (last occurrence), quotes stripped
    local v
    v="$(grep -E "^[[:space:]]*$1=" "${BASE_ENV}" | tail -n1 | cut -d= -f2-)" || true
    v="${v%\"}"; v="${v#\"}"; v="${v%\'}"; v="${v#\'}"
    printf '%s' "${v}"
}

# Secret names must not also live in the plain-text settings file.
for name in "${REQUIRED_SECRETS[@]}" "${FORBIDDEN[@]}"; do
    if grep -qE "^[[:space:]]*${name}=" "${BASE_ENV}"; then
        die "${name} must not be set in ${BASE_ENV} (it is a secret or derived value)"
    fi
done

GCP_PROJECT="${GCP_PROJECT:-$(base_value GCP_PROJECT)}"
if [ -z "${GCP_PROJECT}" ]; then
    GCP_PROJECT="$(curl -fsS -H 'Metadata-Flavor: Google' \
        http://metadata.google.internal/computeMetadata/v1/project/project-id)" \
        || die "GCP_PROJECT unset and metadata server unreachable"
fi

declare -A VAL=()

fetch() {  # fetch NAME -> VAL[NAME]; returns 1 if unavailable
    local name="$1" v
    if v="$(gcloud secrets versions access latest --secret="${SECRET_PREFIX}${name}" \
            --project="${GCP_PROJECT}" --quiet 2>/dev/null)"; then
        VAL["${name}"]="${v}"
        return 0
    fi
    return 1
}

for name in "${REQUIRED_SECRETS[@]}"; do
    fetch "${name}" || die "required secret ${SECRET_PREFIX}${name} unavailable in ${GCP_PROJECT}"
    [ -n "${VAL[${name}]}" ] || die "secret ${SECRET_PREFIX}${name} is empty"
done
for name in "${OPTIONAL_SECRETS[@]}"; do
    if fetch "${name}"; then
        if grep -qE "^[[:space:]]*${name}=" "${BASE_ENV}"; then
            log "note: ${name} from Secret Manager overrides ${BASE_ENV}"
        fi
    fi
done

# ── derived values ───────────────────────────────────────────────────────────
redis_pw="${VAL[REDIS_PASSWORD]}"
[[ "${redis_pw}" =~ ^[A-Za-z0-9._~-]+$ ]] \
    || die "REDIS_PASSWORD must be URL-safe ([A-Za-z0-9._~-]; use: openssl rand -hex 32)"
VAL[CELERY_BROKER_URL]="redis://:${redis_pw}@redis:6379/0"
VAL[CELERY_RESULT_BACKEND]="redis://:${redis_pw}@redis:6379/1"

orthanc_user="${VAL[ORTHANC_USERNAME]:-$(base_value ORTHANC_USERNAME)}"
[ -n "${orthanc_user}" ] || die "ORTHANC_USERNAME missing (secret or ${BASE_ENV})"
VAL[ORTHANC_BASIC_AUTH]="$(printf '%s:%s' "${orthanc_user}" "${VAL[ORTHANC_PASSWORD]}" | base64 -w0)"

# ── write atomically ─────────────────────────────────────────────────────────
tmp="$(mktemp "${MRCV_DIR}/.env.XXXXXX")"
trap 'rm -f -- "${tmp}"' EXIT
{
    printf '# GENERATED by ops/providers/gcp/render-env.sh at %s - do not edit.\n' "$(date -u +%FT%TZ)"
    printf '# Settings: %s   Secrets: Secret Manager (%s, prefix %s)\n\n' \
        "${BASE_ENV}" "${GCP_PROJECT}" "${SECRET_PREFIX}"
    # Drop settings-file lines for anything supplied below, so each name appears once.
    skip="$(printf '%s|' "${!VAL[@]}")"
    grep -vE "^[[:space:]]*(${skip%|})=" "${BASE_ENV}" || true
    printf '\n# ---- secrets / derived (Secret Manager) ----\n'
    for name in $(printf '%s\n' "${!VAL[@]}" | sort); do
        v="${VAL[${name}]}"
        case "${v}" in
            *"'"* | *$'\n'* | *$'\r'*)
                die "secret ${name} contains a quote or newline; not representable in .env" ;;
        esac
        # Single quotes: compose's dotenv parser takes the value literally (no $ expansion).
        printf "%s='%s'\n" "${name}" "${v}"
    done
} > "${tmp}"
chmod 0600 "${tmp}"
chown root:root "${tmp}" 2>/dev/null || true
mv -f -- "${tmp}" "${OUT}"
trap - EXIT

log "wrote ${OUT} (0600): ${#VAL[@]} secret/derived variables: $(printf '%s ' $(printf '%s\n' "${!VAL[@]}" | sort))"
